name: Cypress Master Tests

on:
  push:
    branches:
      - 'master'
      
jobs:
  cypress-run:
    runs-on: ubuntu-latest    
        
    steps:
      - name: Checkout
        uses: actions/checkout@v3        
      - name: Install dep-es
        run: npm install --legacy-peer-deps     
      - name: Cypress run
        run: npm run cypress-smoke:e2e
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
